import { describe, expect, it } from 'vitest';
import { exportMarkdown } from '../export/exportMarkdown';
import type { CanvasObject } from '../store/useCanvasStore';
import type { CommentThread } from '../store/useCommentStore';

describe('exportMarkdown', () => {
  const makeObjects = (): Map<string, CanvasObject> => {
    const map = new Map<string, CanvasObject>();
    map.set('text-1', {
      id: 'text-1',
      type: 'text',
      zIndex: 0,
      data: { text: 'Hello World', x: 100, y: 50 },
    });
    map.set('shape-1', {
      id: 'shape-1',
      type: 'shape',
      zIndex: 1,
      data: { label: 'Action Item', x: 100, y: 200, region: 'kanban-todo' },
    });
    map.set('parked-1', {
      id: 'parked-1',
      type: 'text',
      zIndex: 2,
      data: { text: 'Deferred topic', parked: true },
    });
    return map;
  };

  const makeThreads = (): Map<string, CommentThread> => {
    const map = new Map<string, CommentThread>();
    map.set('thread-1', {
      id: 'thread-1',
      anchorX: 0,
      anchorY: 0,
      anchorObjectId: null,
      resolved: false,
      replies: [
        {
          id: 'r1',
          threadId: 'thread-1',
          author: 'Alice',
          text: 'Good point',
          createdAt: Date.now(),
        },
      ],
    });
    return map;
  };

  it('includes board name in title', () => {
    const md = exportMarkdown(new Map(), new Map(), 'Test Board');
    expect(md).toContain('# Test Board');
  });

  it('includes text objects sorted by position', () => {
    const md = exportMarkdown(makeObjects(), new Map(), 'Board');
    expect(md).toContain('Hello World');
    expect(md).toContain('Action Item');
  });

  it('includes comments section', () => {
    const md = exportMarkdown(new Map(), makeThreads(), 'Board');
    expect(md).toContain('## Comments');
    expect(md).toContain('**Alice**: Good point');
  });

  it('includes parking lot items', () => {
    const md = exportMarkdown(makeObjects(), new Map(), 'Board');
    expect(md).toContain('## Parking Lot');
    expect(md).toContain('Deferred topic');
  });

  it('excludes parked items from main content', () => {
    const md = exportMarkdown(makeObjects(), new Map(), 'Board');
    // "Deferred topic" should only appear in parking lot, not board content
    const boardContentSection = md.split('## Parking Lot')[0];
    expect(boardContentSection).not.toContain('Deferred topic');
  });

  it('groups by region', () => {
    const md = exportMarkdown(makeObjects(), new Map(), 'Board');
    expect(md).toContain('### Action Item');
  });

  it('includes footer', () => {
    const md = exportMarkdown(new Map(), new Map(), 'Board');
    expect(md).toContain('*Generated by dexDraw*');
  });
});
